### ISSUE TITLE
To Do Week 7 (13-02)

### ISSUE THREAD

**Issue by wikdewaal** [arthur1472/SignAbility#10]
- [ ] Contact opnemen relevante personen / instanties
    - Ouders Veerle
    - Doven instanties (Dovenschap / Nederlands gebarencentrum

- [x] Onderzoeken hoe inovatief daadwerkelijk

- [ ] Uitzoeken soort telefoon

- [x] Tijdsplanning inrichten

- [x] Vullen site / social media / tweakers page

- [x] Bedenken vragen eerste meeting Begeleider / TI docent

**Comment by wikdewaal** [comment]
Oh hier kan ik vast dat zenhub voor gebruiken, Eens even kijken

**Comment by Dennizsss** [comment]
Soort telefoon dat mij het handigst en makkelijkst lijkt is een android smarthphone.
Voorkeur 1 van huawei aangezien die het goedkoopst zijn en anderen in het gemaakte lijstje van telefoons nog niet uit zijn en of geimporteerd moeten worden vanuit het buitenland. Of zelfs niet meer te verkijgen zijn.
