### ISSUE TITLE
Meeting Dick Week 08 (20/02)

### ISSUE THREAD

**Issue by wikdewaal** [arthur1472/SignAbility#13]
- [x] Noodzaak / moment use case diagram, domeinmodel, etc.

- [x] Feedback idee / suggesties

- [x] Wat wil de HU anders dan Sogeti

**Comment by MStronghold** [comment]
NOTULEN

Opdelen Fasen.

- FASE 1:

Onderzoeksrapport en plan van aanpak. Haalbaarheid onderzoeken.
Verdere producten: Functioneel ontwerp waar toepasbaar. (Layer model/componentendiagram)

hoofdzaak; requirementanalyse en keuzes systemen. Vooral; is het mogelijk? 

Planning koppelen aan Sogeti - In grote lijnen hun deadline/events aanhouden, minus 1 week als interne deadline.


Onderzoeksrapport wordt hoofddocument. Deze kunnen we periodiek aan begeleiders tonen ter controle en feedback. Zal bestaan uit hoofdvraag  en deelvragen.

Aanstaande vrijdag 27-2 gaat Lucas onderzoeksrapport toetsen bij Dick Pronk.

Dick: Maak deliverables tastbaar, fundamenteel en werk daar naartoe. 

Deze week onderzoeksvragen opstellen en toetsen bij begeleiders. Doorsturen naar Herbert voor tips over onderzoek van de deelvragen. 

Telefoons uitzoeken. Vraag neerleggen bij Dick, Roelant, en Herbert of we deze kunnen krijgen/lenen.

Voor de HU: Onderzoeksrapport, Plan van aanpak. Functioneel/technisch ontwerp (Kan ook requirementsanalyse zijn.
