### ISSUE TITLE
Afspraak Herbert 28-02

### ISSUE THREAD

**Issue by MStronghold** [arthur1472/SignAbility#24]
Vragenlijst:

- Verslagvorm toetsen

- Feedback Tweakers 

- Planning volgende event/weken

**Comment by MStronghold** [comment]
Aankomende week/dit weekend lijkt me handig, kunnen we werkwijze uiteenzetten en via Sogeti contact leggen met doven/slechthorenden

**Comment by arthur1472** [comment]
Aanwezigheid verplicht!
16:55 op skype aanwezig zijn, alstublieft dankuwel.
