### ISSUE TITLE
Chrome Extension: Toggl Time Tracker

### ISSUE THREAD

**Issue by RyuuMasato** [arthur1472/SignAbility#28]
You can find an extension for our Toggle Time Tracker in the Chrome Extension store.

- [x] Jorrit
- [x] Wik
- [x] Dennis
- [x] Arthur
- [x] Lucas 

Works with Zenhub!!!
![image](https://cloud.githubusercontent.com/assets/11370363/23307915/8feb8f4a-faa9-11e6-8098-7fe31a47dc1e.png)

**Comment by MStronghold** [comment]
http://lmgtfy.com/?q=toggl

**Comment by wikdewaal** [comment]
https://chrome.google.com/webstore/search/toggl?utm_source=chrome-ntp-icon

**Comment by RyuuMasato** [comment]
https://chrome.google.com/webstore/detail/toggl-button-productivity/oejgccbfbmkkpaidnkphaiaecficdnfn?utm_source=chrome-app-launcher-info-dialog

**Comment by RyuuMasato** [comment]
Bij de settings heb je ook Pomodoro timer opties in te stellen
