### ISSUE TITLE
Stukjes website

### ISSUE THREAD

**Issue by arthur1472** [arthur1472/SignAbility#30]
Stukje schrijven over jezelf wat op de website komt te staan.
Dit moet vandaag 27-02-2017 af.

- [x] Lucas
- [x] Arthur

**Comment by MStronghold** [comment]
Ik ben Lucas, een sociale jongen die houdt van een goed gesprek en een kroegje op z’n tijd. Mijn grootste passies zijn moderne media, literatuur en het maken van verre reizen. 
Mijn einddoel is de beste software-ontwikkelaar te worden die ik maar kan zijn, omdat dat het speelveld biedt waar ik al mijn interesses in kan combineren. 
Dit wil ik bereiken door open te staan voor nieuwe ervaringen, veel en met verschillende mensen samen te werken en zoveel mogelijk nieuwe dingen uit te proberen.
