### ISSUE TITLE
Mail Signature instellen

### ISSUE THREAD

**Issue by MStronghold** [arthur1472/SignAbility#34]
- [x] Wik

- [x] Dennis

- [ ] Jorrit

INSTRUCTIES: 
volg install instructies voor jouw emailclient op deze pagina: https://htmlsig.com/signatures/0001CM0FPY 

copy paste onderstaande met edit-instructie van Arthur.

**Aanpassen van de onderstaande code is nodig**
NAAM: Vul hier je eigen naam in.
JOB: Vul hier je job title in. *
EMAIL: Vul hier je SignAbility email in.
+316: Vul dit aan naar je eigen mobiele nummer. *

* Dit zijn velden die optioneel zijn, als je deze niet in wil vullen haal dan de hele waarin hij staat weg.

**Comment by MStronghold** [comment]
`<div style="text-size-adjust: none !important; -ms-text-size-adjust: none !important; -webkit-text-size-adjust: none !important;">
<p style="font-family: Helvetica, Arial, sans-serif; font-size: 10px; line-height: 12px; margin-bottom: 10px;">
  <a style="text-decoration:none" href="https://htmlsig.com/t/000001CM62HP">
    <img src="https://htmlsigs.s3.amazonaws.com/logos/files/000/797/268/landscape/HQlogoSignAbility.png" alt="SignAbility" border="0" height="80" width="80">
  </a>
</p>
<p style="font-family: Helvetica, Arial, sans-serif; font-size: 10px; line-height: 12px; color: rgb(33, 33, 33); margin-bottom: 10px;"><span style="font-weight: bold; color: rgb(33, 33, 33); display: inline;">NAAM</span>
  <span style="display: inline;">/</span> <span style="color: rgb(33, 33, 33); display: inline;">JOB</span>
  <span style="display: inline;"><br></span>
  <a href="mailto:EMAIL" style="color: rgb(71, 124, 204); text-decoration: none; display: inline;">EMAIL</a><span style="display: inline;"> / </span><span style="color: rgb(33, 33, 33); display: inline;">+316</span>
</p>
<p style="font-family: Helvetica, Arial, sans-serif; font-size: 10px; line-height: 12px; margin-bottom: 10px;">
  <span style="font-weight: bold; color: rgb(33, 33, 33); display: inline;">SignAbility</span>
  <span style="display: inline;"><br></span>
  <span style="color: #212121;"></span>
  <span style="color: #212121;"></span>
  <span></span> <span style="color: #212121;"></span>
  <span></span> <span style="color: #212121;"></span>
  <span></span>
  <a href="https://signability.nl" style="color: rgb(71, 124, 204); text-decoration: none; display: inline;">https://signability.nl</a>
</p>
<p style="font-size: 0px; line-height: 0; font-family: Helvetica, Arial, sans-serif;">
  <a style="text-decoration: none; display: inline;" href="https://htmlsig.com/t/000001CEK661">
    <img width="16" style="margin-bottom:2px; border:none; display:inline;" height="16" data-filename="twitter.png" src="https://s3.amazonaws.com/htmlsig-assets/round/twitter.png" alt="Twitter">
  </a>
  <span style="white-space: nowrap; display: inline;">
    <img src="https://s3.amazonaws.com/htmlsig-assets/spacer.gif" width="2">
  </span>
  <a style="text-decoration: none; display: inline;" href="https://htmlsig.com/t/000001CHS63P">
    <img width="16" style="margin-bottom:2px; border:none; display:inline;" height="16" data-filename="facebook.png" src="https://s3.amazonaws.com/htmlsig-assets/round/facebook.png" alt="Facebook">
  </a>
  <span style="white-space: nowrap; display: inline;">
    <img src="https://s3.amazonaws.com/htmlsig-assets/spacer.gif" width="2">
  </span>
  <a style="text-decoration: none; display: inline;" href="https://htmlsig.com/t/000001CFSN20">
    <img width="16" style="margin-bottom:2px; border:none; display:inline;" height="16" data-filename="youtube.png" src="https://s3.amazonaws.com/htmlsig-assets/round/youtube.png" alt="Youtube">
  </a>
  <span style="white-space: nowrap; display: inline;">
    <img src="https://s3.amazonaws.com/htmlsig-assets/spacer.gif" width="2">
  </span>
</p>
<p style="font-family: Helvetica, Arial, sans-serif; color: #212121; font-size: 9px; line-height: 12px;"></p>
</div>`

**Comment by arthur1472** [comment]
**Aanpassen van de onderstaande code is nodig**
**NAAM**: Vul hier je eigen naam in.
**JOB**: Vul hier je job title in. *
**EMAIL**: Vul hier je SignAbility email in.
**+316**: Vul dit aan naar je eigen mobiele nummer. *

\* Dit zijn velden die optioneel zijn, als je deze niet in wil vullen haal dan de hele <span> waarin hij staat weg.

```html
<div style="text-size-adjust: none !important; -ms-text-size-adjust: none !important; -webkit-text-size-adjust: none !important;">
<p style="font-family: Helvetica, Arial, sans-serif; font-size: 10px; line-height: 12px; color: rgb(33, 33, 33); margin-bottom: 10px;"><span style="font-weight: bold; color: rgb(33, 33, 33); display: inline;">NAAM</span>
  <span style="display: inline;">/</span> <span style="color: rgb(33, 33, 33); display: inline;">JOB</span>
  <span style="display: inline;"><br></span>
  <a href="mailto:EMAIL" style="color: rgb(71, 124, 204); text-decoration: none; display: inline;">EMAIL</a><span style="display: inline;"> / </span><span style="color: rgb(33, 33, 33); display: inline;">+316</span>
</p>
<p style="font-family: Helvetica, Arial, sans-serif; font-size: 10px; line-height: 12px; margin-bottom: -20px;">
  <a style="text-decoration:none" href="https://signability.nl">
    <img src="https://htmlsigs.s3.amazonaws.com/logos/files/000/797/268/landscape/HQlogoSignAbility.png" alt="SignAbility" border="0" height="80" width="80">
  </a>
</p>
<p style="font-family: Helvetica, Arial, sans-serif; font-size: 10px; line-height: 12px; margin-bottom: 10px;">
  <span style="font-weight: bold; color: rgb(33, 33, 33); display: inline;">SignAbility</span>
  <span style="display: inline;"><br></span>
  <span style="color: #212121;"></span>
  <span style="color: #212121;"></span>
  <span></span> <span style="color: #212121;"></span>
  <span></span> <span style="color: #212121;"></span>
  <span></span>
  <a href="https://signability.nl" style="color: rgb(71, 124, 204); text-decoration: none; display: inline;">https://signability.nl</a>
</p>
<p style="font-size: 0px; line-height: 0; font-family: Helvetica, Arial, sans-serif;">
  <a style="text-decoration: none; display: inline;" href="https://twitter.com/sign_ability">
    <img width="16" style="margin-bottom:2px; border:none; display:inline;" height="16" data-filename="twitter.png" src="https://s3.amazonaws.com/htmlsig-assets/round/twitter.png" alt="Twitter">
  </a>
  <span style="white-space: nowrap; display: inline;">
    <img src="https://s3.amazonaws.com/htmlsig-assets/spacer.gif" width="2">
  </span>
  <a style="text-decoration: none; display: inline;" href="https://www.facebook.com/SignAbility-165460923957602/">
    <img width="16" style="margin-bottom:2px; border:none; display:inline;" height="16" data-filename="facebook.png" src="https://s3.amazonaws.com/htmlsig-assets/round/facebook.png" alt="Facebook">
  </a>
  <span style="white-space: nowrap; display: inline;">
    <img src="https://s3.amazonaws.com/htmlsig-assets/spacer.gif" width="2">
  </span>
  <a style="text-decoration: none; display: inline;" href="https://www.youtube.com/channel/UC4lN-1girbU936Bh9Ozvlnw">
    <img width="16" style="margin-bottom:2px; border:none; display:inline;" height="16" data-filename="youtube.png" src="https://s3.amazonaws.com/htmlsig-assets/round/youtube.png" alt="Youtube">
  </a>
  <span style="white-space: nowrap; display: inline;">
    <img src="https://s3.amazonaws.com/htmlsig-assets/spacer.gif" width="2">
  </span>
</p>
<p style="font-family: Helvetica, Arial, sans-serif; color: #212121; font-size: 9px; line-height: 12px;"></p>
</div>
```
