### ISSUE TITLE
EnableTalk mailen met vragen over project

### ISSUE THREAD

**Issue by MStronghold** [arthur1472/SignAbility#45]
- http://enabletalk.com/

EnableTalk is vergelijkbaar project met handschoenen. Deze heeft een award gewonnen, maar lijkt te zijn stilgevallen. Echter nog wel de moeite waard om navraag te doen naar bevindingen.

**Comment by Dennizsss** [comment]
mail@enabletalk.com

**Comment by Dennizsss** [comment]
gemailed nu nog wachten/hopen op antwoord

**Comment by Dennizsss** [comment]
Geen reactie
GG
